### your site title here

title: Rahil Makadia
description: Ph.D. Candidate | University of Illinois at Urbana-Champaign
baseurl: "" #name of GitHub repository
url: "https://rahil-makadia.github.io/website" #custom url to be used instead of GitHub repository
email: makadia2@illinois.edu

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
# twitter: "#"
linkedin: "rahil-makadia"
# stackoverflow: "#"
github: "rahil-makadia"
researchgate: "rahil-makadia"
orcid: "0000-0001-9265-2230"
# quora: "#"
# instagram: "#"
# facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
