title: Rahil Makadia
description: Ph.D. Candidate at UIUC
baseurl: ""
url: "https://rahil-makadia.github.io"
email: makadia2@illinois.edu
first_name: Rahil
last_name: Makadia
author: Rahil Makadia
lang: en
keywords: "Rahil, Makadia, UIUC, planetary defense, asteroids, comets, spacecraft"

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
# twitter: "#"
linkedin: "rahil-makadia"
# stackoverflow: "#"
github: "rahil-makadia"
researchgate: "rahil-makadia"
orcid: "0000-0001-9265-2230"
google-scholar: "m1jVeSMAAAAJ"
ads: "Makadia,Rahil"
# quora: "#"
# instagram: "#"
# facebook: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - dart.md
      - grss.md
      - orex.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
